GGStores/Models/ActorModel.cs
using System.ComponentModel.DataAnnotations;

namespace GGStores.Models
{
    public class ActorModel
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Profile Picture")]
        [Required(ErrorMessage = "Profile Picture is required")]
        public string ProfilePicture { get; set; }

        [Display(Name = "Full name")]
        [Required(ErrorMessage = "Full Name is required")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Full Name must be between 3 and 50 chars ")]
        public string FullName { get; set; }

        [Display(Name = "Bio")]
        [Required(ErrorMessage = "Bio is required")]
        public string Bio { get; set; }


        public List<Actor_Movie>? Actor_Movies { get; set; }
    }
}

GGStores/Models/Actor_Movie.cs
namespace GGStores.Models
{
    public class Actor_Movie
    {
        public int Movieid { get; set; }
        public Movie Movie { get; set; }
        public int ActorId { get; set; }

        public ActorModel Actor { get; set; }

    }
}

GGStores/Models/Cinema.cs
using System.ComponentModel.DataAnnotations;

namespace GGStores.Models
{
    public class Cinema
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Cinema Logo")]
        public string Logo { get; set; }
        [Display(Name = "Cinema Name")]
        public string Name { get; set; }
        [Display(Name = "Cinema Description")]
        public string Description { get; set; }
        public List<Movie> Movies { get; set; }
    }
}

GGStores/Models/ErrorViewModel.cs
namespace GGStores.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GGStores/Models/Movie.cs
using GGStores.Data.Enum;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GGStores.Models
{
    public class Movie
    {
        [Display(Name = "Movie Name")]
        public string Name { get; set; }
        [Key]
        public int Id { get; set; }

        [Display(Name = "Movie Discription")]
        public string Description { get; set; }
        public double Price { get; set; }

        [Display(Name = "Movie Image")]
        public string ImageUrl { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public MovieCategory MovieCategory { get; set; }


        public List<Actor_Movie> Actor_Movies { get; set; }

        public int CinemaId { get; set; }
        [ForeignKey("CinemaId")]
        public Cinema Cinema { get; set; }



        public int ProducerId { get; set; }
        [ForeignKey("ProducerId")]
        public Producer Producer { get; set; }



    }
}

GGStores/Models/Producer.cs
using System.ComponentModel.DataAnnotations;

namespace GGStores.Models
{
    public class Producer
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Profile Picture")]
        public string ProfilePicture { get; set; }
        [Display(Name = "Full Name")]
        public string FullName { get; set; }
        [Display(Name = "Biography")]
        public string Bio { get; set; }

        public List<Movie> Movies { get; set; }
    }
}

GGStores/Controllers/ActorsController.cs
using GGStores.Data.Interface;
using GGStores.Models;
using Microsoft.AspNetCore.Mvc;

namespace GGStores.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorsService _actorsService;

        public ActorsController(IActorsService actorsService)
        {
            _actorsService = actorsService;
        }
        public async Task<IActionResult> Index()
        {
            var data = await _actorsService.GetAllAsync();
            return View(data);
        }

        public IActionResult Create()
        {
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePicture,Bio")] ActorModel actor)
        {



            if (!ModelState.IsValid)
            {
                return View(actor);
            }

            await _actorsService.AddAsync(actor);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var actorDetails = await _actorsService.GetByIdAsync(id);


            if (actorDetails == null)
            {
                return View("NotFound");
            }
            return View(actorDetails);


        }


        public async Task<IActionResult> Edit(int id)
        {
            var actorDetails = await _actorsService.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }



        [HttpPost]
        public async Task<IActionResult> Edit(int id, ActorModel request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            await _actorsService.UpdateAsync(id, request);
            return RedirectToAction(nameof(Index));


        }
        public async Task<IActionResult> Delete(int id)
        {
            var actorDetails = await _actorsService.GetByIdAsync(id);
            if (actorDetails == null) return View("Notfound");
            return View(actorDetails);
        }



        [HttpPost]
        public async Task<IActionResult> DeleteAsync(int id)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }

            await _actorsService.DeleteAsync(id);

            return RedirectToAction(nameof(Index));


        }
    }
}

GGStores/Controllers/CinemaController.cs
using GGStores.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GGStores.Controllers
{
    public class CinemaController : Controller
    {
        private readonly StoreDbContext _storeContext;
        public CinemaController(StoreDbContext storeDbContext)
        {
            _storeContext = storeDbContext;
        }
        public async Task<IActionResult> Index()
        {
            var allCinemass = await _storeContext.cinema.ToListAsync();

            return View(allCinemass);
        }


    }
}

GGStores/Controllers/MovieController.cs
using GGStores.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GGStores.Controllers
{
	public class MovieController : Controller
	{
		private readonly StoreDbContext _storeContext;
		public MovieController(StoreDbContext storeDbContext)
		{
			_storeContext = storeDbContext;
		}
		public async Task<IActionResult> Index()
		{
			var allMovies = await _storeContext.Movie.Include(n => n.Cinema).OrderBy(n => n.Name).ToListAsync();

			return View(allMovies);
		}
	}
}

GGStores/Controllers/ProducerController.cs
using GGStores.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GGStores.Controllers
{
    public class ProducerController : Controller
    {
        private readonly StoreDbContext _storeContext;
        public ProducerController(StoreDbContext storeDbContext)
        {
            _storeContext = storeDbContext;
        }
        public async Task<IActionResult> Index()
        {
            var producers = await _storeContext.producer.ToListAsync();

            return View(producers);
        }
    }
}

GGStores/Views/Actors/Create.cshtml
@model ActorModel;

@{
    ViewData["Title"] = "Add a new actor";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Add a new Actor</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview" class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePicture" class="control-label"></label>
                        <input asp-for="ProfilePicture"  class="form-control" />

                        <span asp-validation-for="ProfilePicture" class="text-design text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-design text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" />
                        <span asp-validation-for="Bio" class="text-design text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
 </div>

    @section Scripts {
        <script>
            $(document).ready(function () {
                
                   var output = document.getElementById('ProfilePicturePreview')
                   output.src = $("#ProfilePicture").val();
                
            });

            $("#ProfilePicture").on("change", function(){
            var output = document.getElementById('ProfilePicturePreview')
            output.src = $(this).val();
            })
        </script>
    }

GGStores/Views/Actors/Delete.cshtml
@model ActorModel;

@{
    ViewData["Title"] = "Add a new actor";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Delete Actor</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Delete">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview" class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePicture" class="control-label"></label>
                        <input asp-for="ProfilePicture" class="form-control" />

                        <span asp-validation-for="ProfilePicture" class="text-design text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-design text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" />
                        <span asp-validation-for="Bio" class="text-design text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Delete" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {

            var output = document.getElementById('ProfilePicturePreview')
            output.src = $("#ProfilePicture").val();

        });

        $("#ProfilePicture").on("change", function () {
            var output = document.getElementById('ProfilePicturePreview')
            output.src = $(this).val();
        })
    </script>
    }

GGStores/Views/Actors/Details.cshtml
@model ActorModel;

@{
    ViewData["Title"] = "Add a new actor";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Details for @Model.FullName</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">  
                    <div class="form-group text-center">
                        <img  class="border-info rounded-circle" style="max-width: 150px" id="ProfilePicturePreview" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePicture" class="control-label"></label>
                        <input asp-for="ProfilePicture" class="form-control" readonly/>

                        <span asp-validation-for="ProfilePicture" class="text-design text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" readonly/>
                        <span asp-validation-for="FullName" class="text-design text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" readonly />
                        <span asp-validation-for="Bio" class="text-design text-danger"></span>
                    </div>
                    <div class="form-group">
                       
                        <a class=" btn btn-outline-success float-right"asp-action="Edit" asp-route-id="@Model.Id">Edit</a>

                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
               
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {

            var output = document.getElementById('ProfilePicturePreview')
            output.src = $("#ProfilePicture").val();

        });

    </script>
    }

GGStores/Views/Actors/Edit.cshtml
@model ActorModel;

@{
    ViewData["Title"] = "Add a new actor";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Update Actor</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview" class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePicture" class="control-label"></label>
                        <input asp-for="ProfilePicture" class="form-control" />

                        <span asp-validation-for="ProfilePicture" class="text-design text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-design text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" />
                        <span asp-validation-for="Bio" class="text-design text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {

            var output = document.getElementById('ProfilePicturePreview')
            output.src = $("#ProfilePicture").val();

        });

        $("#ProfilePicture").on("change", function () {
            var output = document.getElementById('ProfilePicturePreview')
            output.src = $(this).val();
        })
    </script>
    }

GGStores/Views/Actors/Index.cshtml
@model IEnumerable<ActorModel>;

@{
    ViewData["Title"] = "list of actors";
}


<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead class="text-center">
                <tr>
                    <th class="px-2">@Html.DisplayNameFor(model => model.ProfilePicture)</th>
                    <th class="px-2">@Html.DisplayNameFor(model => model.FullName)</th>
                    <th class="px-2">@Html.DisplayNameFor(model => model.Bio)</th>
                    <th class="px-2">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                    <tr class="text-center">
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.ProfilePicture" style="max-width: 150px"/>
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Bio)
                        </td>
                        <td class="align-middle">
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit</a>
                            <a class="btn btn-outline-info"  asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details</a>
                            <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete</a>

                        </td>
                    </tr>
                }
            </tbody>
            
        </table>
    </div>
</div>

<div class="text-success" style="position:fixed; right: 25px; bottom: 25px;  ">
    <a asp-controller="Actors" asp-action="Create" class="btn btn-success"><i class="bi bi-plus-circle"></i>Add New</a> 
</div>

GGStores/Views/Actors/NotFound.cshtml
<div class="row">
    <div class="col-md-offset-3">
        <h1 class="text-danger">
            youve the end of the internet
        </h1>

        <hr />
        <a class="btn btn-outline-success" asp-controller="Movie" asp-action="Index">Home Page</a>
    </div>
</div>

GGStores/Views/Cinema/Index.cshtml
@model IEnumerable<Cinema>;

@{
    ViewData["Title"] = "list of Cinemas";
}


<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead class="text-center">
                <tr>
                    <th class="px-2">@Html.DisplayNameFor(model => model.Logo)</th>
                    <th class="px-2">@Html.DisplayNameFor(model => model.Name)</th>
                    <th class="px-2">@Html.DisplayNameFor(model => model.Description)</th>
                    <th class="px-2">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="text-center">
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.Logo" style="max-width: 150px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td class="align-middle">
                           <a class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i>Edit</a>
                            <a class="btn btn-danger"><i class="bi bi-trash"></i>Delete</a>

                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>

GGStores/Views/Movie/Index.cshtml
@model IEnumerable<Movie>

@{
	ViewData["Title"] = "list of Movies";
}


   

<div class="text-white  "  style="max-width: 100%">
	@foreach (var item in Model)
			{

		<div class="row itms itemcont">
			
			@*<div class="col-md-4 col-xs-6 col-sm-6 col-lg-4">
				<div class="movie-card bxs3" data-movie="IT3">
					<div class="movie-card__overlay"></div>
					<div class="movie-card__share">
						<button class="movie-card__icon">
							<i class="fa fa-heart"><img src="@item.ImageUrl" class="img-fluid" /></i>
						</button>
						@*<button class="movie-card__icon">
							<i class="fa fa-star"></i>
						</button>
						<button class="movie-card__icon">
							<i class="fa fa-tv"></i>
						</button>*@
					@*</div>
					<div class="movie-card__content">
						<div class="movie-card__header">
							<h1 class="movie-card__title">Something Item</h1>
							<h4 class="movie-card__info">(2019) Sci-Fi, Thriller</h4>
						</div>
						<p class="movie-card__desc">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sollicitudin, elit in aliquet tincidunt, augue elit fermentum augue. Donec.</p>
						<button class="btn btn-outline movie-card__button" type="button">Details</button>
					</div>
				</div>
			</div>*@ 
			<div class="col-md-6 col-xs-6 col-sm-6 col-lg-6 " style="width: 100%">
				<div class="movie-card bxs4" data-movie="IT1">
					<div class="movie-card__overlay"></div>
					<div class="movie-card__share">
						
						<button class="movie-card__icon" >
							<i class="fa fa-tv"><img src="@item.ImageUrl" class="img-fluid movie-image" style=""/></i>
						</button>
					</div>
					<div class="movie-card__content">
						<div class="movie-card__header">
							<h1 class="movie-card__title">@item.Name</h1>
							<h4 class="movie-card__info">@item.MovieCategory</h4>
						</div>
						<p class="movie-card__desc">@item.Description</p>
						<div class="card-footer">
							<b>
								Status: @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
								{
									<span class="badge bg-success text-white"> AVAILABLE</span>
								}
								else if (DateTime.Now > item.EndDate)
								{
									<span class="badge bg-success text-white"> No Show</span>
								}else
								{
									<span class="badge bg-primary text-white">UPCOING</span>
								}
							</b>
							
							<button class="btn btn-outline movie-card__button" type="button">Details</button>
							<button class="btn btn-outline movie-card__button" type="button">Add to cart (Price @item.Price.ToString("c"))</button>
						</div>
					</div>
				</div>
			</div> 
		</div>
			}

</div>

	

GGStores/Views/Producer/Index.cshtml
@model IEnumerable<Producer>;

@{
    ViewData["Title"] = "list of Producers";
}


<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead class="text-center">
                <tr>
                    <th class="px-2">@Html.DisplayNameFor(model => model.ProfilePicture)</th>
                    <th class="px-2">@Html.DisplayNameFor(model => model.FullName)</th>
                    <th class="px-2">@Html.DisplayNameFor(model => model.Bio)</th>
                    <th class="px-2">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="text-center">
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.ProfilePicture" style="max-width: 150px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Bio)
                        </td>
                        <td class="align-middle">
                            <a class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i>Edit</a>
                            <a class="btn btn-outline-info"><i class="bi bi-eye"></i>Details</a>
                            <a class="btn btn-danger"><i class="bi bi-trash"></i>Delete</a>

                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>

GGStores/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GGStores</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GGStores.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
   
</head>
<body id="back-ground" style="padding-top: 70px;">
    <header class="" style="position: fixed; top: 0; z-index: 1000; width: 100%;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  text-white box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movie" asp-action="Index">GGStores</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-start" style="position: relative; left: 170px;">
                    <ul class="navbar-nav d-flex">
                        <li class="navbar-nav flex-grow-1">
                            <a class="nav-link" asp-controller="Movie" asp-action="Index"><i class="badge-info bi bi-film"></i>Movies</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-gear"></i>Management
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Cinema" asp-action="Index"><i class="bi bi-camera-reels"></i>Cinema</a>
                                <a class="dropdown-item" asp-controller="Producer" asp-action="Index"><i class="bi bi-headset"></i>Producers</a>
                                <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-square"></i>Actors</a>
                            </div>
                        </li>
                    </ul>

                    <form class="form-inline my-2 my-lg-0 d-flex" asp-controller="Movie" asp-action="Filter" style="padding-right: 25px;">
                        
                            <!-- Add a form-group wrapper -->
                            <input name="searchString" type="text" class="form-contro" placeholder="Search......." style="width: 800px; height:40px">
                       
                        
                            <!-- Add a form-group wrapper -->
                            <button class="btn btn-outline-success my-2 my-sm-0 form-contro"  type="submit"><i class="bi bi-search"></i></button>
                        
                    </form>

                </div>
            </div>
        </nav>

    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3 text-white">
            @RenderBody() 
        </main>
    </div>

    <footer class=" footer text-muted">
        <div class="container">
            &copy; 2023 - GGStores 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>